import { isDeepStrictEqual } from 'node:util'
import openapiTS, { astToString } from 'openapi-typescript'

const BANNER = `// Generated by \`npm run api:types\` from the backend's OpenAPI schema (openapi.json beside it).
// Don't edit it: change the backend, then run the command again.
`

/** schema.d.ts's text for an OpenAPI document's text. */
export async function generateTypes(schemaText: string): Promise<string> {
  const ast = await openapiTS(JSON.parse(schemaText))
  return BANNER + astToString(ast)
}

type Document = { paths?: object; components?: { schemas?: object } }

function names(document: unknown, part: 'paths' | 'schemas'): Set<string> {
  const doc = document as Document
  return new Set(Object.keys((part === 'paths' ? doc.paths : doc.components?.schemas) ?? {}))
}

/** How two schemas differ, one line per path or schema only one of them has; [] if they're equal. */
export function describeDrift(committed: unknown, other: unknown): string[] {
  if (isDeepStrictEqual(committed, other)) return []
  const lines: string[] = []
  for (const part of ['paths', 'schemas'] as const) {
    const ours = names(committed, part)
    const theirs = names(other, part)
    for (const name of theirs) if (!ours.has(name)) lines.push(`${part} ${name}: only the backend has it`)
    for (const name of ours) if (!theirs.has(name)) lines.push(`${part} ${name}: only the committed schema has it`)
  }
  return lines.length > 0 ? lines : ['same paths and schemas, but their details differ']
}
