// Generated by `npm run design:numbers` (web/scripts/design-numbers.ts) from the web app spec. Don't
// edit it: after a new handoff, run the command again. Live's own layout numbers; the stage's are in
// src/stage/design-numbers.ts, which only the stage's lazy chunk loads.
export const LIVE_LAYOUT = {
  "widePx": 1200,
  "phoneStage": {
    "width": 390,
    "height": 268
  }
} as const
