// Generated by `npm run design:numbers` (web/scripts/design-numbers.ts) from the web app spec
// (LIVE_SPEC) and the pinned reference renders (LIVE_RENDER). Don't edit it: after a new handoff, run
// the command again. The numbers everything outside the stage draws with; the stage's are in
// src/stage/design-numbers.ts, which only the stage's lazy chunk loads. A colour is a tokens.css
// custom property where tokens.css has it, else the render's own hex.
export const LIVE_SPEC = {
  "widePx": 1200,
  "phoneStage": {
    "width": 390,
    "height": 268
  },
  "swatch": {
    "px": 14,
    "phonePx": 12,
    "tablePx": 16,
    "fromColour": "#1e1c19",
    "mixBase": 0.15,
    "glowPx": 10,
    "darkAt": 0.04,
    "darkColour": "#26241f",
    "pillRatio": 1.9,
    "ownEffectPx": 1.5,
    "ownEffectOffsetPx": 2,
    "streamedPx": 1.5,
    "streamedOffsetPx": 2,
    "offlinePx": 1.5,
    "switchedOffPx": 1.5
  },
  "reducedMotionMs": 1000,
  "tape": {
    "framePx": 6,
    "phoneFramePx": 5,
    "panelBarPx": 6
  },
  "frozenCardsOpacity": 0.45,
  "attentionPopoverPx": 430
} as const

export const LIVE_RENDER = {
  "pip": {
    "rest": "--color-control-hover",
    "lit": "--color-text",
    "riseBeats": 0.02,
    "holdBeats": 0.56,
    "endBeats": 1,
    "glowPx": 10,
    "glow": "--color-text",
    "glowAlpha": 0.55
  },
  "overlay": {
    "background": "#221d12",
    "border": "#5a4a24",
    "ink": "#ffcf5c",
    "track": "#3a311a",
    "fill": "#ffcf5c"
  }
} as const
