// Generated by `npm run design:numbers` (web/scripts/design-numbers.ts) from the web app spec
// (SPEC) and the pinned reference renders (RENDER). Don't edit it: after a new handoff, run the
// command again. A colour is a tokens.css custom property where tokens.css has it, else the
// render's own hex.
export const SPEC = {
  "floorEdgePx": 0.8,
  "balconyHatchDeg": 45,
  "window": {
    "sillM": 0.45,
    "glassAlpha": 0.1,
    "edgePx": 1.1,
    "edgeAlpha": 0.45
  },
  "glassDoorSillM": 0.02,
  "columnAboveCutM": 0.02,
  "ghostAlpha": 0.075,
  "camera": {
    "turnDeg": 14,
    "tiltDeg": 55
  },
  "fit": {
    "heightM": 2.3,
    "sidePx": 56,
    "topPx": 70,
    "bottomPx": 64
  },
  "rotate": {
    "maxDeg": 45,
    "stepDeg": 15
  },
  "samples": {
    "point": 1,
    "cylinderTall": 6,
    "cylinderTallerThanM": 0.3,
    "cylinderShort": 2,
    "line": 6,
    "bentLine": 10,
    "grid": 7
  },
  "core": {
    "px": 3.4,
    "liftBase": 0.35,
    "liftPerIntensity": 0.3,
    "darkPx": 3
  },
  "halo": {
    "pointPx": 14,
    "base": 0.5,
    "perIntensity": 0.7,
    "stripPx": 9,
    "falloff": {
      "centre": 0.9,
      "mid": 0.28,
      "midAt": 0.22
    }
  },
  "pool": {
    "baseM": 1.15,
    "perZ": 0.6,
    "intensityBase": 0.55,
    "perIntensity": 0.6,
    "multiSample": 0.72,
    "falloff": {
      "centre": 0.95,
      "mid": 0.35,
      "midAt": 0.25
    }
  },
  "stripPx": {
    "min": 3,
    "max": 4
  },
  "dropLine": {
    "dashPx": 2,
    "gapPx": 2,
    "alpha": 0.18
  },
  "frozen": {
    "grayscale": 0.85,
    "brightness": 0.55
  },
  "dprCap": 2,
  "phoneFps": 30,
  "target": {
    "fps": 60,
    "leds": 412,
    "pools": 60
  },
  "label": {
    "capsPx": 9.5,
    "lookPx": 15
  },
  "reducedMotionMs": 1000,
  "swatch": {
    "fromColour": "#1e1c19",
    "mixBase": 0.15,
    "glowPx": 10,
    "darkAt": 0.04,
    "darkColour": "#26241f",
    "ownEffectPx": 1.5,
    "ownEffectOffsetPx": 2,
    "offlinePx": 1.5,
    "switchedOffPx": 1.5
  },
  "widePx": 1200,
  "phoneStage": {
    "width": 390,
    "height": 268
  },
  "quality": {
    "desktopFps": 55,
    "phoneFps": 30,
    "idle": 0.5
  }
} as const

export const RENDER = {
  "stage": {
    "widthPx": 964,
    "heightPx": 840
  },
  "dropLine": {
    "widthPx": 0.8
  },
  "floorTick": {
    "radiusPx": 2.2,
    "colour": "--color-text",
    "alpha": 0.25
  },
  "switchedOff": {
    "ringPx": 4.2,
    "fill": "--color-bg",
    "colour": "--color-text",
    "alpha": 0.55,
    "widthPx": 1.1,
    "slashHalfPx": 3
  },
  "offlineStrip": {
    "colour": "--color-text",
    "alpha": 0.35,
    "widthPx": 2,
    "dashPx": 3,
    "gapPx": 3
  },
  "ghost": {
    "widthPx": 0.9
  },
  "strip": {
    "darkColour": "--color-line-strong"
  },
  "furniture": {
    "sideFacing": "#1a1815",
    "sideOther": "#161411",
    "edge": {
      "colour": "--color-text",
      "alpha": 0.06,
      "widthPx": 0.8
    }
  },
  "sun": {
    "path": {
      "colour": "--color-text",
      "alpha": 0.28,
      "widthPx": 1,
      "dashPx": 2,
      "gapPx": 4
    },
    "glow": {
      "radiusPx": 46,
      "colour": "#ffae52",
      "stops": [
        {
          "at": 0,
          "alpha": 0.95
        },
        {
          "at": 0.2,
          "alpha": 0.35
        },
        {
          "at": 1,
          "alpha": 0
        }
      ]
    },
    "disc": {
      "radiusPx": 7,
      "colour": "#ffd2a0"
    },
    "label": {
      "dyPx": 22,
      "weight": 500,
      "font": 10.5,
      "colour": "--color-text-2"
    }
  },
  "label": {
    "lineGapPx": 16
  },
  "courtyard": {
    "dotSpacingPx": 7,
    "dotRadiusPx": 0.8,
    "dotColour": "--color-line-soft",
    "opacity": 0.9
  },
  "balcony": {
    "hatchSpacingPx": 6,
    "hatchColour": "--color-stage-floor-edge",
    "hatchWidthPx": 1
  },
  "legend": {
    "leftPx": 20,
    "bottomPx": 18,
    "gapPx": 16,
    "font": 11.5,
    "colour": "--color-text-3",
    "itemGapPx": 6,
    "dotPx": 10,
    "liveSample": "#c8f25a",
    "glowPx": 8,
    "glowAlpha": 0.6,
    "ownEffectSample": "#ff9a2a"
  },
  "controls": {
    "rightPx": 20,
    "bottomPx": 16,
    "gapPx": 6
  },
  "tools": {
    "leftPx": 20,
    "topPx": 16,
    "gapPx": 12
  },
  "readout": {
    "rightPx": 20,
    "topPx": 18,
    "gapPx": 8,
    "font": "--text-data",
    "colour": "--color-text-2",
    "iconPx": 15,
    "iconColour": "#ffb45a"
  },
  "tooltip": {
    "dxPx": 17,
    "dyPx": -81,
    "widthPx": 206,
    "nameGapPx": 8,
    "swatchPx": 12,
    "swatchGlowPx": 10,
    "leader": {
      "lengthPx": 49,
      "widthPx": 1,
      "colour": "#5a564e",
      "angleDeg": -69.7
    }
  },
  "ownEffect": {
    "ringPx": 7.5,
    "colour": "--color-text",
    "alpha": 0.7,
    "widthPx": 0.9,
    "dashPx": 1.5,
    "gapPx": 2
  },
  "streamedCopy": {
    "dxPx": 7,
    "dyPx": -6,
    "risePx": 3,
    "halfPx": 6,
    "rowGapPx": 3.5,
    "colour": "--color-text",
    "alpha": 0.8,
    "widthPx": 1
  }
} as const
